version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo installing composer..
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
